package dev.gamma.modules.basehunting;

import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraft.core.Direction;

/**
 * Block states that imply somebody has spent time in a chunk, as opposed to blocks that merely
 * don't belong there.
 *
 * <p>{@link SusChunkFinder}'s original list works on block identity: a crafting table underground
 * was placed by a player, end of story. These are a different kind of evidence and need the
 * block <em>state</em>, not just the block. Most of them are growth stages, and growth only
 * advances on random ticks, which only fire inside somebody's simulation distance. A plant that
 * has finished growing is therefore a record of how long that chunk has been loaded — which is
 * exactly what a base is: a place a player keeps loaded. Naturally generated terrain that nobody
 * has visited stays frozen at whatever worldgen produced.
 *
 * <p>Each signal is independently toggleable because they are not equally trustworthy, and which
 * ones are worth having on depends on the world. The two ends of that range:
 *
 * <ul>
 * <li>{@link #isRotatedDeepslate} is close to proof. Worldgen only ever places deepslate with a
 *     vertical axis; the horizontal ones exist solely because a player placed a block against a
 *     wall. There is no natural false positive.</li>
 * <li>{@link #isFullyGrownAmethyst} is the weakest, since geodes generate containing some finished
 *     clusters already. It earns its place on volume — a geode that is <em>entirely</em> clusters
 *     had something sitting next to it — which is why {@code SusChunkFinder} thresholds on a count
 *     per chunk rather than firing on a single match.</li>
 * </ul>
 */
final class GrowthSignal {

	private GrowthSignal() {
	}

	/** Fully grown amethyst. Buds are ignored: an unfinished bud is evidence of the opposite. */
	static boolean isFullyGrownAmethyst(BlockState state) {
		return state.is(Blocks.AMETHYST_CLUSTER);
	}

	/**
	 * Kelp that has stopped growing. {@code KELP} is the living top of a column and carries the
	 * age; {@code KELP_PLANT} is inert stem below it. A column at max age has run out of room or
	 * time, and reaching age 25 from a worldgen height takes a great many random ticks.
	 */
	static boolean isMatureKelp(BlockState state) {
		return state.is(Blocks.KELP)
				&& state.hasProperty(BlockStateProperties.AGE_25)
				&& state.getValue(BlockStateProperties.AGE_25) >= BlockStateProperties.MAX_AGE_25;
	}

	/**
	 * Glow berries on a cave vine. Berries grow in on a random tick and worldgen places plenty of
	 * bare vine, so berried vine deep in a cave means those chunks have been ticking.
	 */
	static boolean isBerriedCaveVine(BlockState state) {
		return (state.is(Blocks.CAVE_VINES) || state.is(Blocks.CAVE_VINES_PLANT))
				&& state.hasProperty(BlockStateProperties.BERRIES)
				&& state.getValue(BlockStateProperties.BERRIES);
	}

	/**
	 * Vines. Unlike the rest, this is a spread signal rather than a growth-stage one — vines
	 * propagate to neighbouring blocks over time, so a lot of them underground means a long-loaded
	 * chunk. Weak on its own, and the reason it is off by default in jungle-heavy worlds is left
	 * to the user.
	 */
	static boolean isVine(BlockState state) {
		return state.is(Blocks.VINE);
	}

	/** Fully grown cocoa. Worldgen places cocoa at age 0, so age 2 is always the result of ticking. */
	static boolean isFullyGrownCocoa(BlockState state) {
		return state.is(Blocks.COCOA)
				&& state.hasProperty(BlockStateProperties.AGE_2)
				&& state.getValue(BlockStateProperties.AGE_2) >= BlockStateProperties.MAX_AGE_2;
	}

	/**
	 * Bamboo that has finished its growth stage. Bamboo generated by worldgen starts young, and a
	 * mature stalk is a lot of random ticks — this is one of the better signals in a jungle, where
	 * a bare "is there bamboo" check would be useless.
	 */
	static boolean isMatureBamboo(BlockState state) {
		return state.is(Blocks.BAMBOO)
				&& state.hasProperty(BlockStateProperties.STAGE)
				&& state.getValue(BlockStateProperties.STAGE) > 0;
	}

	/**
	 * A bee nest with honey in it. Honey level climbs on random ticks and resets when harvested, so
	 * a full nest means nobody has touched it <em>and</em> the chunk has been loaded a long time.
	 */
	static boolean isFullBeeNest(BlockState state) {
		return state.is(Blocks.BEE_NEST)
				&& state.hasProperty(BlockStateProperties.LEVEL_HONEY)
				&& state.getValue(BlockStateProperties.LEVEL_HONEY) >= 5;
	}

	/**
	 * Deepslate placed on its side. Worldgen only ever produces {@code AXIS=Y} deepslate, so any
	 * other axis is a block a player placed — most often the tell-tale trail of someone walling off
	 * a tunnel with the stone they just mined. The strongest signal here by a distance, and the one
	 * worth leaving on everywhere.
	 */
	static boolean isRotatedDeepslate(BlockState state) {
		return state.is(Blocks.DEEPSLATE)
				&& state.hasProperty(BlockStateProperties.AXIS)
				&& state.getValue(BlockStateProperties.AXIS) != Direction.Axis.Y;
	}
}
